<?php include_once('../classes/session.php');?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>KurshanLab Strain Database</title>
  </head>
  <body>
    <?php
      require_once('../classes/classes_gene_elements.php');

      $isEntityBeingEdited = $_POST['originalAlleleEdited'];

      if ($isEntityBeingEdited) {
        $theOriginalAlleleName = $_POST['original_allele_letters_postvar'] . $_POST['original_allele_numbers_postvar'];
        $theOldComment = $_POST['originalComment_htmlName'];
        $theOldSelectedGene = $_POST['originalSelectedGene_htmlName'];
        $theOldAlleleID = $_POST['original_allele_id_postvar'];
      }
      // if I switch from externally-produced to lab-produced, this name is NOT valid!

      $theNewComment = $_POST['comments_postvar'];

      // this array contains the selected gene in the first element

      if ( (isset($_POST['genes'])) && ($_POST['genes'][0] != "")){
        $theNewSelectedGene = $_POST['genes'];
      } else $theNewSelectedGene[0] = NULL;

      // common sequence code for plasmids and alleles
      require_once("../sequence/submit_sequence.php");

      // if it's not being edited
      if (!$isEntityBeingEdited) {
        $theAlleleName = "";
        // new entry is totally different from edited entry
        if ($_POST["manufacturedWhere_htmlName"] == "externally-sourced") {
          $theAlleleName = $_POST['geneElementLetters_htmlName'] . $_POST['geneElementNumbers_htmlName'];
          $newAlleleObject = new Allele($theAlleleName, $theNewComment,$theNewSelectedGene[0],$theSequenceFileName,$theSequenceFileData);
          // we are passing the selected gene to it.
					if (!($newAlleleObject->doesItAlreadyExist())) {
  					$newAlleleObject->insertOurEntry();
            ourheader("location: ../start/start.php"); //BUG this was missing
					}
				}
				else {
					//$theAlleleName is not actually used here; name is built within insertOurEntryWithCounterTableUpdate
					// we are passing the selected gene to it.
					$newAlleleObject = new Allele($theAlleleName, $theNewComment,$theNewSelectedGene[0],$theSequenceFileName,$theSequenceFileData);
          // new, so sequence data gets put in automatically
          $newAlleleObject->insertOurEntryWithCounterTableUpdate();
          ourheader("location: ../start/start.php");
				}
      } else {
        $switchedState ="";
        if ($_POST['original_allele_letters_postvar'] == 'kur') {
        	if ($_POST['manufacturedWhere_htmlName'] == "externally-sourced") {
        		$switchedState = "toExternallySourced";
        	 } else {
        		$switchedState = "stayingOnLabProduced";
        	}
        } else {
        	if ($_POST['manufacturedWhere_htmlName'] == "lab-produced") {
        		$switchedState = "toLabProduced";
        	} else {
        		$switchedState = "stayingOnExternallySourced";
        	}
        }
        require_once('../classes/classes_gene_elements.php');

        switch ($switchedState) {
          // if we are go to a “to” state, then we are submitting the allele for an update regardless
        	case "toExternallySourced":
            // externally sourced gets the new name as programmed above
            // but first we ensure that the new name doesn't conflict with an existing record
            $theNewAlleleName = $_POST['geneElementLetters_htmlName'] . $_POST['geneElementNumbers_htmlName'];
            $newAlleleObject= new Allele($theNewAlleleName, $theNewComment,$theNewSelectedGene[0],$theSequenceFileName,$theSequenceFileData);
        		if(!$newAlleleObject->doesItAlreadyExist()){
              // updates sequence data automatically
              $newAlleleObject->updateOurEntry($theOldAlleleID);
              ourheader("location: ../start/start.php");
            } else {
              echo "<br>The allele you submitted, " . $theNewAlleleName . ", is already in the database.<br>";
            }
        		break;

          case "toLabProduced":

            // allele name is auto-generated by insertOurEntryWithCounterTableUpdate
            // new method updateOurEntryWithCounterTableUpdate creates a new counter record but keeps the allele into the existing record
        		$newAlleleObject = new Allele("", $theNewComment,$theNewSelectedGene[0],$theSequenceFileName,$theSequenceFileData);
            // updates sequence data automatically
            $newAlleleObject->updateOurEntryWithCounterTableUpdate($theOldAlleleID);
            ourheader("location: ../start/start.php");
            break;

          case "stayingOnLabProduced":
            // we pass it the original name and just update
            // we always update this state for some reason
            $newAlleleObject = new Allele($theOriginalAlleleName, $theNewComment,$theNewSelectedGene[0],$theSequenceFileName,$theSequenceFileData);
            // updates sequence data automatically
            $newAlleleObject->updateOurEntry($theOldAlleleID);
            ourheader("location: ../start/start.php");
            break;

          case "stayingOnExternallySourced":
            // we may or may not have edited the name;
            // if we edited it, then check that the new name is not a duplicate
            // but if we didn't edit it, don't check because that original name will be flagged inadvertently as a duplicate
            $checkForNewNameForDuplicate = false;
            $theNewAlleleName = $_POST['geneElementLetters_htmlName'] . $_POST['geneElementNumbers_htmlName'];
            $newAlleleObject = new Allele($theNewAlleleName, $theNewComment,$theNewSelectedGene[0],$theSequenceFileName,$theSequenceFileData);
            if ($theOriginalAlleleName != $theNewAlleleName) {
              $checkForNewNameForDuplicate = true;
            }
            if ($checkForNewNameForDuplicate) {
              if(!$newAlleleObject->doesItAlreadyExist()){
                // updates sequence data automatically
                $newAlleleObject->updateOurEntry($theOldAlleleID);
                ourheader("location: ../start/start.php");
              } else {
                echo "<br>The allele you submitted, " . $theOriginalAlleleName . ", is already in the database.<br>";
              }
            } else {
              // updates sequence data automatically
              $newAlleleObject->updateOurEntry($theOldAlleleID);
              ourheader("location: ../start/start.php");
            }
            break;
        }
      }
     ?>
  </body>
</html>
